packages:
  - apps/*
  - packages/*
allowBuilds:
  "@node-rs/argon2": true
  esbuild: true
  sharp: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - drizzle-orm@0.45.4
  - pg-boss@12.37.1
verifyDepsBeforeRun: false
