/** POS sale with loyalty card, coupon and points on PGlite (legacy `posSell` + wrapper 9940). */
import { PGlite } from '@electric-sql/pglite';
import { eq, sql } from 'drizzle-orm';
import { drizzle } from 'drizzle-orm/pglite';
import { migrate } from 'drizzle-orm/pglite/migrator';
import { fileURLToPath } from 'node:url';
import { beforeAll, describe, expect, it } from 'vitest';
import { retailPrice, stock } from '@wise/core';
import { impAuto } from '@wise/core/retail';
import { importRows } from './retail-items';
import * as schema from './schema/index';
import { seedReference } from './seed/reference';
import { loadStockContext, replaceSourceMoves } from './stock-service';
import type { Actor } from './stock-docs';
import { saveCoupon, saveLoyaltyCard } from './retail';
import { deleteStoreOut, posSaleWithLoyalty, postFiskRead, saveStoreOut } from './parity-retail';

const db = drizzle(new PGlite(), { schema });
type DB = typeof db;
let A: Actor;
let firmId = '';
const I: Record<string, string> = {};
const tx = <T>(f: (t: DB) => Promise<T>) => db.transaction((t) => f(t as unknown as DB));
const err = async (p: Promise<unknown>) => { try { await p; } catch (e) { return e as Error; } throw new Error('expected an error'); };

beforeAll(async () => {
  await migrate(db, { migrationsFolder: fileURLToPath(new URL('../migrations', import.meta.url)) });
  await seedReference(db);
  // the migration for `store_outs` (schema/parity-retail.ts) is generated by the coordinator; create it here if missing
  await db.execute(sql`create table if not exists store_outs (id uuid primary key default gen_random_uuid(), firm_id uuid not null references firms(id) on delete cascade,
    kind text not null, number text not null, date date not null, location_id uuid, partner_id uuid references partners(id), ref text, account text,
    lines jsonb not null default '[]', note text, sales_day_id uuid, created_by uuid, created_at timestamptz not null default now(), updated_at timestamptz not null default now())`);
  const [f] = await db.insert(schema.firms).values({ name: 'Маркет ДООЕЛ', vatRegistered: true }).returning();
  firmId = f!.id;
  A = { firmId, userId: null };
  const rows = await db.insert(schema.items).values([
    { firmId, code: '001', name: 'Кафе', type: 'goods', unit: 'ком', price: '59', vatRate: 18 },
    { firmId, code: '002', name: 'Леб', type: 'goods', unit: 'ком', price: '105', vatRate: 5 },
  ]).returning();
  for (const r of rows) I[r.code!] = r.id;
  await tx((t) => replaceSourceMoves(t, {
    firmId, sourceType: 'purchase', sourceId: 'P-1', date: '2026-01-05', userId: null,
    moves: [
      { id: '', date: '2026-01-05', item: I['001']!, qty: 10, value: 300, type: 'in', wh: 'main', lines: [] },
      { id: '', date: '2026-01-05', item: I['002']!, qty: 10, value: 600, type: 'in', wh: 'main', lines: [] },
    ],
  }));
}, 120_000);

describe('posSaleWithLoyalty', () => {
  it('card discount + coupon: discount lines per rate, points, coupon use, stock issued', async () => {
    await tx((t) => saveLoyaltyCard(t, A, { number: '2800000001', name: 'Ана', phone: '070 123 456', discount: 10, points: 0 }));
    await tx((t) => saveCoupon(t, A, { code: 'JESEN', kind: 'amt', value: 20.7, maxUses: 1 }));
    const cart = [{ itemId: I['001']!, qty: 2, price: 59, rate: 18 }, { itemId: I['002']!, qty: 1, price: 105, rate: 5 }];
    const r = await tx((t) => posSaleWithLoyalty(t, A, { date: '2026-03-02', cart, cardNo: '070123456', coupon: 'jesen' }));
    expect(r.total).toBe(223);
    expect(r.disc).toBe(43); // 22.30 card 10 % + 20.70 coupon
    expect(r.pay).toBe(180);
    expect(r.card).toEqual({ name: 'Ана', earn: 1, red: 0, points: 1 });
    const [d] = await db.select().from(schema.salesDaily).where(eq(schema.salesDaily.id, r.id));
    expect(Number(d!.total)).toBe(180);
    expect(d!.lines.filter((l) => !l.itemId).map((l) => [l.rate, l.price])).toEqual([[5, -20.25], [18, -22.75]]);
    const [c] = await db.select().from(schema.loyaltyCards).where(eq(schema.loyaltyCards.number, '2800000001'));
    expect([Number(c!.points), Number(c!.spent), c!.visits]).toEqual([1, 180, 1]);
    const [cp] = await db.select().from(schema.coupons).where(eq(schema.coupons.code, 'JESEN'));
    expect(cp!.used).toBe(1);
    const L = await loadStockContext(db, firmId);
    expect(stock(L.ctx, I['001']!).qty).toBe(8);
    // a used-up coupon is refused, nothing is booked
    expect((await err(tx((t) => posSaleWithLoyalty(t, A, { date: '2026-03-02', cart, coupon: 'JESEN' })))).message).toBe('Купонот е веќе искористен.');
    expect((await err(tx((t) => posSaleWithLoyalty(t, A, { date: '2026-03-02', cart, cardNo: '999' })))).message).toMatch(/не е пронајдена/);
  });
});

describe('store sale / supplier return (m_izlez)', () => {
  it('sale books the turnover and issues goods; return issues to 2200; stock is checked; delete restores', async () => {
    const L0 = await loadStockContext(db, firmId);
    const q0 = stock(L0.ctx, I['002']!).qty;
    const s = await tx((t) => saveStoreOut(t, A, { kind: 'sale', date: '2026-05-04', account: '1009', lines: [{ itemId: I['002']!, qty: 2, price: 100 }] }));
    expect(s.number).toBe('ПР-001/26');
    const [o] = await db.select().from(schema.storeOuts).where(eq(schema.storeOuts.id, s.id));
    const [d] = await db.select().from(schema.salesDaily).where(eq(schema.salesDaily.id, o!.salesDayId!));
    expect([Number(d!.total), d!.number, d!.fisk?.cashK]).toEqual([200, 'ПР-001/26', '1009']);
    expect(stock((await loadStockContext(db, firmId)).ctx, I['002']!).qty).toBe(q0 - 2);
    const P = (await db.insert(schema.partners).values({ firmId, name: 'Добавувач', code: '9' }).returning())[0]!.id;
    expect((await err(tx((t) => saveStoreOut(t, A, { kind: 'ret', date: '2026-05-04', lines: [{ itemId: I['002']!, qty: 1 }] })))).message).toBe('Изберете добавувач.');
    expect((await err(tx((t) => saveStoreOut(t, A, { kind: 'ret', date: '2026-05-04', partnerId: P, lines: [{ itemId: I['002']!, qty: 999 }] })))).message).toMatch(/Нема доволно залиха/);
    const r = await tx((t) => saveStoreOut(t, A, { kind: 'ret', date: '2026-05-04', partnerId: P, ref: 'Ф-1', lines: [{ itemId: I['002']!, qty: 1 }] }));
    expect(r.number).toBe('ПВ-001/26');
    const mv = await db.select().from(schema.stockMoves).where(eq(schema.stockMoves.sourceId, r.id));
    expect(mv[0]!.lines.some((l) => l.account === '2200' && l.partnerId === P)).toBe(true);
    await tx((t) => deleteStoreOut(t, A, s.id));
    expect((await db.select().from(schema.salesDaily).where(eq(schema.salesDaily.id, o!.salesDayId!))).length).toBe(0);
    expect(stock((await loadStockContext(db, firmId)).ctx, I['002']!).qty).toBe(q0 - 1);
  });
});

describe('retail stock-list import (m_lager)', () => {
  it('receipt into a store creates missing items with unit, VAT rate and the store retail price', async () => {
    const store = (await db.insert(schema.codes).values({ firmId, cb: 'store', code: '07', name: 'Продавница 7' }).returning())[0]!.id;
    const hdr = ['Шифра', 'Назив', 'Ед.мера', 'Количина', 'Набавна цена', 'Продажна цена со ДДВ', 'ДДВ %', 'Баркод'];
    const map = impAuto('in', hdr);
    expect(map).toMatchObject({ code: 0, name: 1, unit: 2, qty: 3, cost: 4, mpc: 5, rate: 6, barcode: 7 });
    const r = await tx((t) => importRows(t, { ...A, role: 'admin' }, 'in', [{ code: 'R1', name: 'Сок 1л', unit: 'шише', qty: 12, cost: 40, mpc: 70, rate: 5, barcode: '5310000000099' }], { date: '2026-06-01', wh: store, today: '2026-06-01' }));
    expect(r.add).toBe(1);
    const [it] = await db.select().from(schema.items).where(eq(schema.items.code, 'R1'));
    expect([it!.unit, it!.vatRate]).toEqual(['шише', 5]);
    const L = await loadStockContext(db, firmId);
    expect(stock(L.ctx, it!.id, store).qty).toBe(12);
    expect(retailPrice(L.ctx.items!.find((x) => x.id === it!.id)!, store)).toBe(70);
  });
});

describe('postFiskRead', () => {
  const read = {
    device: 'AC240119487', from: '2026-04-01', to: '2026-04-02',
    days: [
      { date: '2026-04-01', z: '11', gross: { 'А': 1180, 'Б': 105 }, vat: { 'А': 180, 'Б': 5 }, total: 1285, cash: 1000, card: 285, receipts: 7 },
      { date: '2026-04-02', z: '12', gross: { 'А': 590 }, vat: { 'А': 90 }, total: 590, cash: 590 },
    ],
  };
  const fisk = () => db.select().from(schema.salesDaily).where(eq(schema.salesDaily.kind, 'fisk'));
  it('posts each day, replaces on a repost, keeps the days of a single posting, issues goods', async () => {
    const r = await tx((t) => postFiskRead(t, A, { read, today: '2026-04-10', nonVat: false, sum: false, sc: 'trg' }));
    expect(r.ids).toHaveLength(2);
    expect(r.total).toBe(1875);
    await tx((t) => postFiskRead(t, A, { read, today: '2026-04-10', nonVat: false, sum: false, sc: 'trg' }));
    const S = await fisk();
    expect(S).toHaveLength(2);
    const d1 = S.find((s) => s.date === '2026-04-01')!;
    expect([d1.number, Number(d1.card), d1.count, d1.fisk?.device, d1.fisk?.sc]).toEqual(['11', 285, 7, 'AC240119487', 'trg']);
    expect(d1.groups.map((g) => [g.rate, g.base + g.vat]).sort()).toEqual([[18, 1180], [5, 105]]);
    const s = await tx((t) => postFiskRead(t, A, { read, today: '2026-04-10', nonVat: false, sum: true, sc: 'trg', issue: true, meth: 'fifo' }));
    expect(s.ids).toHaveLength(1);
    const [one] = await db.select().from(schema.salesDaily).where(eq(schema.salesDaily.id, s.ids[0]!));
    expect(one!.days?.map((d) => d.date)).toEqual(['2026-04-01', '2026-04-02']);
    expect(s.issued).toBeGreaterThan(0);
    const [f] = await db.select().from(schema.firms).where(eq(schema.firms.id, firmId));
    expect((f!.settings as { fiskOpt?: { sc?: string } }).fiskOpt?.sc).toBe('trg');
  });
});
