/**
 * Retail / materials DB flows on PGlite: manual receipts and issues, customer orders → invoice drafts and deliveries,
 * supplier orders, promotions (levelling start / end), write-off without a BOM, item merge, imports.
 * The retail tables are created from the schema with drizzle-kit's API (their migration is generated by the coordinator).
 */
import { PGlite } from '@electric-sql/pglite';
import { and, eq, sql } from 'drizzle-orm';
import { drizzle } from 'drizzle-orm/pglite';
import { migrate } from 'drizzle-orm/pglite/migrator';
import { fileURLToPath } from 'node:url';
import { beforeAll, describe, expect, it } from 'vitest';
import { stock } from '@wise/core';
import * as schema from './schema/index';
import * as retailSchema from './schema/retail';
import { seedReference } from './seed/reference';
import { loadStockContext, replaceSourceMoves } from './stock-service';
import type { Actor } from './stock-docs';
import {
  cancelCustomerOrder, createSupplierOrders, deleteManualMove, deleteWriteoff, invoiceFromOrder, orderDeliveries, runPromotion, saveCoupon,
  saveCustomerOrder, saveLoyaltyCard, saveLots, saveManualMove, savePromotion, saveWriteoff, setSupplierOrderStatus,
} from './retail';
import { assignInternalBarcodes, importRows, mergeItems, setItemRoles, setItemUnits } from './retail-items';

const db = drizzle(new PGlite(), { schema });
type DB = typeof db;
let A: Actor & { role: string };
let firmId = '';
const I: Record<string, string> = {};
let store = '';
let cust = '';

const tx = <T>(f: (t: DB) => Promise<T>) => db.transaction((t) => f(t as unknown as DB));
const err = async (p: Promise<unknown>) => { try { await p; } catch (e) { return e as Error; } throw new Error('expected an error'); };
const qty = async (item: string, wh?: string) => stock((await loadStockContext(db, firmId)).ctx, item, wh).qty;

beforeAll(async () => {
  await migrate(db, { migrationsFolder: fileURLToPath(new URL('../migrations', import.meta.url)) });
  const { generateDrizzleJson, generateMigration } = await import('drizzle-kit/api');
  const without = Object.fromEntries(Object.entries(schema).filter(([k]) => !(k in retailSchema)));
  for (const s of await generateMigration(generateDrizzleJson(without), generateDrizzleJson({ ...schema }))) await db.execute(sql.raw(s));
  await seedReference(db);
  const [f] = await db.insert(schema.firms).values({ name: 'Маркет ДООЕЛ' }).returning();
  firmId = f!.id;
  A = { firmId, userId: null, role: 'admin' };
  const [p] = await db.insert(schema.partners).values({ firmId, name: 'Купувач', code: '1' }).returning();
  cust = p!.id;
  const rows = await db.insert(schema.items).values([
    { firmId, code: '001', name: 'Кафе', type: 'goods', unit: 'ком', price: '100', vatRate: 18 },
    { firmId, code: '002', name: 'Kafe', type: 'goods', unit: 'kom', price: '100', vatRate: 18 },
    { firmId, code: '100', name: 'Брашно', type: 'material', unit: 'кг', vatRate: 5 },
    { firmId, code: '200', name: 'Леб', type: 'product', unit: 'ком', price: '30', vatRate: 5 },
  ]).returning();
  for (const r of rows) I[r.code!] = r.id;
  store = (await db.insert(schema.codes).values({ firmId, cb: 'store', code: '02', name: 'Продавница 1' }).returning())[0]!.id;
  await tx((t) => replaceSourceMoves(t, {
    firmId, sourceType: 'purchase', sourceId: 'P-1', date: '2026-01-05', userId: null,
    moves: [
      { id: '', date: '2026-01-05', item: I['001']!, qty: 10, value: 600, type: 'in', wh: 'main', lines: [] },
      { id: '', date: '2026-01-05', item: I['100']!, qty: 50, value: 1250, type: 'in', wh: 'main', lines: [] },
    ],
  }));
}, 120_000);

describe('manual receipts / issues / transfers (zaliha)', () => {
  it('receipt with posting, issue at average cost, transfer, delete', async () => {
    const r = await tx((t) => saveManualMove(t, A, { kind: 'in', date: '2026-02-01', itemId: I['001']!, qty: 10, price: 80, account: '2200', partnerId: cust }));
    expect(await qty(I['001']!)).toBe(20);
    const [j] = await db.select().from(schema.journals).where(and(eq(schema.journals.sourceType, 'stock:manual_move'), eq(schema.journals.sourceId, r.id)));
    expect(j).toBeTruthy();
    const u = await tx((t) => saveManualMove(t, A, { kind: 'use', date: '2026-02-02', itemId: I['001']!, qty: 2, account: '4000' }));
    const [m] = await db.select().from(schema.stockMoves).where(eq(schema.stockMoves.sourceId, u.id));
    expect(Number(m!.value)).toBe(-140); // avg (600 + 800) / 20 = 70
    expect((await err(tx((t) => saveManualMove(t, A, { kind: 'use', date: '2026-02-02', itemId: I['001']!, qty: 99 })))).message).toMatch(/Нема доволно/);
    await tx((t) => saveManualMove(t, A, { kind: 'tr', date: '2026-02-03', itemId: I['001']!, qty: 3, from: 'main', to: store }));
    expect(await qty(I['001']!, store)).toBe(3);
    await tx((t) => deleteManualMove(t, A, u.id));
    expect(await qty(I['001']!)).toBe(20);
  });
});

describe('customer and supplier orders', () => {
  it('order → invoice draft for what is on stock; deliveries counted', async () => {
    const o = await tx((t) => saveCustomerOrder(t, A, { date: '2026-03-01', partnerId: cust, lines: [{ itemId: I['001']!, qty: 25, price: 100 }] }));
    expect(o.number).toBe('НР-001/2026');
    const r = await tx((t) => invoiceFromOrder(t, A, o.id, '2026-03-02'));
    expect(r.short).toBe(true);
    const [inv] = await db.select().from(schema.invoices).where(eq(schema.invoices.id, r.invoiceId));
    expect(inv!.status).toBe('draft');
    const d = (await orderDeliveries(db, firmId)).get(o.id)!;
    expect(d[I['001']!]).toBe(20); // limited to the 20 on stock (all locations)
    await tx((t) => cancelCustomerOrder(t, A, o.id));
  });
  it('supplier orders grouped by supplier, received', async () => {
    const made = await tx((t) => createSupplierOrders(t, A, [{ itemId: I['100']!, qty: 5, price: 25, pid: null }, { itemId: I['001']!, qty: 2, price: 60, pid: cust }], 'repl', '2026-03-05'));
    expect(made).toEqual(['НД-001/2026', 'НД-002/2026']);
    const [po] = await db.select().from(schema.supplierOrders).where(eq(schema.supplierOrders.number, 'НД-001/2026'));
    await tx((t) => setSupplierOrderStatus(t, A, po!.id, 'recv', '2026-03-06'));
    expect((await err(tx((t) => setSupplierOrderStatus(t, A, po!.id, 'cancel', '2026-03-06')))).message).toMatch(/не е отворена/);
  });
});

describe('loyalty, promotions, write-off, lots', () => {
  it('cards and coupons are unique per firm', async () => {
    await tx((t) => saveLoyaltyCard(t, A, { number: '2800000001', name: 'Ана' }));
    expect((await err(tx((t) => saveLoyaltyCard(t, A, { number: '2800000001', name: 'Б' })))).message).toMatch(/постои/);
    await tx((t) => saveCoupon(t, A, { code: 'jesen', kind: 'pct', value: 10 }));
    expect((await err(tx((t) => saveCoupon(t, A, { code: 'JESEN', kind: 'amt', value: 5 })))).message).toMatch(/постои/);
  });
  it('promotion start and end create levellings', async () => {
    await db.update(schema.items).set({ data: { sp: { [store]: 120 } } }).where(eq(schema.items.id, I['001']!));
    const p = await tx((t) => savePromotion(t, A, { name: 'Пролет', wh: store, from: '2026-04-01', to: '2026-04-10', pct: 10, sel: { [I['001']!]: {} } }));
    const s = await tx((t) => runPromotion(t, A, p.id, false, '2026-04-02'));
    expect(s.date).toBe('2026-04-02');
    const e = await tx((t) => runPromotion(t, A, p.id, true, '2026-04-20'));
    expect(e.date).toBe('2026-04-11');
    const L = await db.select().from(schema.levellingDocs).where(eq(schema.levellingDocs.firmId, firmId));
    expect(L.map((d) => [d.date, d.lines[0]!.old, d.lines[0]!.new, d.lines[0]!.qty])).toEqual(expect.arrayContaining([['2026-04-02', 120, 108, 3], ['2026-04-11', 108, 120, 3]]));
  });
  it('write-off without BOM issues materials and receives the product', async () => {
    const w = await tx((t) => saveWriteoff(t, A, { date: '2026-05-31', from: '2026-05-01', to: '2026-05-31', mode: 'popis', productId: I['200']!, productQty: 100, lines: [{ itemId: I['100']!, qty: 10 }] }));
    expect(w.total).toBe(250);
    expect(await qty(I['200']!)).toBe(100);
    await tx((t) => deleteWriteoff(t, A, w.id));
    expect(await qty(I['100']!)).toBe(50);
  });
  it('lots on production orders need an existing document', async () => {
    expect((await err(tx((t) => saveLots(t, A, [{ sourceType: 'production', sourceId: crypto.randomUUID(), lineNo: 0, lot: 'L1' }])))).message).toMatch(/не постои/);
  });
});

describe('items: units, roles, barcodes, merge, import', () => {
  it('units, roles and internal barcodes', async () => {
    expect(await tx((t) => setItemUnits(t, A, { kom: 'ком' }))).toBe(1);
    const r = await tx((t) => setItemRoles(t, A, [{ id: I['200']!, role: 'prod' }], '3100'));
    expect(r.missing).toEqual(['Леб']);
    expect(await tx((t) => assignInternalBarcodes(t, A))).toBe(4);
    expect(await tx((t) => assignInternalBarcodes(t, A))).toBe(0);
  });
  it('merge moves references and keeps the old name as an alias', async () => {
    await tx((t) => saveManualMove(t, A, { kind: 'in', date: '2026-06-01', itemId: I['002']!, qty: 1, price: 10 }));
    const r = await tx((t) => mergeItems(t, A, I['001']!, [I['001']!, I['002']!]));
    expect(r.merged).toBe(1);
    expect(r.refs).toBeGreaterThan(0);
    const [m] = await db.select().from(schema.items).where(eq(schema.items.id, I['001']!));
    expect((m!.data as { aliases?: string[] }).aliases).toContain('Kafe');
    expect(await db.select().from(schema.items).where(eq(schema.items.id, I['002']!))).toHaveLength(0);
    expect(await qty(I['001']!)).toBe(21);
  });
  it('imports items, opening stock and a count', async () => {
    const r = await tx((t) => importRows(t, A, 'items', [{ name: 'Чај', code: '500', price: 50, rate: 5 }, { name: 'Кафе голем', code: '001' }, { name: '' }], { date: '2026-07-01', today: '2026-07-01' }));
    expect([r.add, r.upd, r.skip.length]).toEqual([1, 1, 1]);
    const s = await tx((t) => importRows(t, A, 'in', [{ code: '500', qty: 10, cost: 30, mpc: 59 }, { code: '777', name: 'Нов', qty: 2 }], { date: '2026-07-01', wh: store, today: '2026-07-01' }));
    expect(s.add).toBe(1);
    const [tea] = await db.select().from(schema.items).where(and(eq(schema.items.firmId, firmId), eq(schema.items.code, '500')));
    expect(await qty(tea!.id, store)).toBe(10);
    expect((tea!.data as { sp?: Record<string, number> }).sp?.[store]).toBe(59);
    await tx((t) => importRows(t, A, 'pop', [{ code: '500', cnt: 8 }], { date: '2026-07-02', wh: store, today: '2026-07-02' }));
    expect(await qty(tea!.id, store)).toBe(8);
    const j = await tx((t) => importRows(t, A, 'journal', [{ date: '2026-07-03', k: '1000', d: 100 }, { date: '2026-07-03', k: '9000', p: 100 }, { date: '2026-07-04', k: '1000', d: 5 }], { date: '2026-07-03', today: '2026-07-03' }));
    expect(j.add).toBe(1);
    expect(j.skip[0]).toMatch(/рамнотежа/);
  });
});
