/**
 * Document-reading prompts, ported verbatim from legacy `index.html` (LEGACY-MAP C.6). Do not edit the wording:
 * the post-processing (`@wise/core/sales` fixLines/fixRates/…) is tuned to these exact instructions.
 *
 * Wired here: PUR_PROMPT (purchases, skan/masovno), SALE_PROMPT (issued sales invoices), SCR_PROMPT (supplier returns).
 * Ported for the coordinator to wire through `readDocument` later: IMP_PROMPT (import documents), BLG_PROMPT
 * (cash-register receipts, Phase 4 — TODO(ai)), EMP_PROMPT (employment documents, Phase 6 — TODO(ai)).
 */

/** Legacy `PUR_PROMPT` (4665–4668). */
export const PUR_PROMPT = `This is an invoice (фактура) received by a company in North Macedonia. Extract it. Reply with ONLY JSON:
{"supplierName":string,"supplierEdb":string,"buyerName":string (the company that RECEIVED the invoice – купувач/примач),"buyerEdb":string,"number":string,"date":"YYYY-MM-DD","art32":boolean,"groups":[{"rate":18|10|5|0,"base":number,"vat":number,"kind":"material"|"service"|"energy"|"goods"|"asset"|"other"}],"lines":[{"code":string,"barcode":string,"name":string,"unit":string,"qty":number,"price":number,"discount":number,"amount":number,"rate":number}],"total":number}
Rules: NEVER take the quantity from the ДДВ % / Д.С. / Стапка column (18, 10, 5 are VAT rates). QUANTITY: many invoices have both a packages column (Пак, Пакување, Амб., Кут., Колети, Pkg) and a quantity column (Количина, Кол., Qty). "qty" MUST be the QUANTITY column in base units (e.g. 80,000 pieces), NEVER the number of packages. "price" = price per ONE base unit without VAT (after discount if the discount is applied per line), "discount" = line discount % (0 if none), "amount" = the line value without VAT as printed. Check that qty × price ≈ amount; if not, you probably took the packages column – fix it. VAT: each line's VAT rate is in the column Д.С. / ДДВ % / Стапка (18, 10 or 5). "groups" MUST be copied from the VAT recapitulation table printed at the bottom (Основица / ДДВ per rate, e.g. 5% 30.166,67 / 1.508,33 and 10% 1.379,09 / 137,91) and "total" from За наплата / Вкупно за плаќање. NUMBER FORMAT: Macedonian invoices use comma as the DECIMAL separator and dot as thousands separator: "80,000" means 80 (eighty), "1.333,34" means 1333.34, "0,400" means 0.4. Return plain JSON numbers (80, 1333.34, 0.4). code = the supplier's article code / шифра printed on the line ("" if none); barcode = EAN/баркод if printed ("" if none). amounts in denars as plain numbers; price = unit price without VAT. groups = totals grouped by VAT rate and kind (goods = bought for resale, material = raw material for production, asset = equipment). art32=true if the invoice says "пренесување на даночна обврска" or "член 32-а" (vat 0). ЕДБ = 13-digit tax number of the SUPPLIER (issuer), not the buyer. Keep names in the original language.
SEVERAL INVOICES: if the document contains more than one separate invoice (different invoice numbers – e.g. several invoices scanned into one PDF, each starting with its own header), return {"invoices":[{…one object as above per invoice…}]} in the order they appear, each with its own supplier, number, date, groups, lines and total. A multi-page single invoice is ONE invoice.`;

/** Legacy `SALE_PROMPT` (8379–8382) — a function of the own firm. */
export const SALE_PROMPT = (firm: { name?: string | null; edb?: string | null }) => `This is a SALES invoice (излезна фактура) ISSUED BY the company "${firm.name || ''}" (ЕДБ ${firm.edb || ''}) in North Macedonia to a customer. Extract it. The BUYER (купувач / примач) is the other party, NOT the issuer. Reply with ONLY JSON:
{"number":string,"date":"YYYY-MM-DD","dueDate":"YYYY-MM-DD","buyerName":string,"buyerEdb":string,"buyerAddress":string,"buyerCity":string,"art32":boolean,"groups":[{"rate":18|10|5|0,"base":number,"vat":number}],"lines":[{"code":string,"barcode":string,"name":string,"unit":string,"qty":number,"price":number,"discount":number,"amount":number,"rate":number}],"total":number}
Rules: "number" = the invoice number exactly as printed (e.g. 125/2026). COLUMNS: Macedonian invoices usually have columns like Р.бр | Шифра | Назив | Ед.м. | Количина | Цена без ДДВ | Рабат % | ДДВ % (Д.С.) | Износ. "qty" MUST come from the Количина / Кол. column – NEVER from the ДДВ % / Д.С. / Стапка column (values like 18, 10, 5 are usually the VAT rate, not the quantity). Before answering, verify for EVERY line that qty × price ≈ amount (the Износ/Вредност column as printed); if it does not match you took the wrong column – fix it. "qty" = quantity in base units (not packages). "price" = price per unit WITHOUT VAT after line discount; "amount" = line value without VAT as printed; check qty × price ≈ amount. "rate" = the VAT rate of the line (18, 10, 5 or 0). "groups" = the VAT recapitulation (основица and ДДВ per rate). "total" = total amount to pay incl. VAT. Numbers as plain numbers (1.234,50 → 1234.5). art32 = true if the invoice says член 32-а / пренесување на даночна обврска.
SEVERAL INVOICES: if the document contains more than one invoice (different numbers), return {"invoices":[{…one object per invoice…}]} in order. A multi-page single invoice is ONE invoice.`;

/** Legacy `IMP_PROMPT` (4350–4361) — import documents (invoice, ЕЦД, forwarding, transport). */
export const IMP_PROMPT = `You receive ONE document related to an IMPORT of goods into North Macedonia. Identify its type and extract data. Reply with ONLY JSON:
{"type":"supplier_invoice"|"customs_declaration"|"transport"|"forwarding"|"other_cost",
 "issuerName":string,"issuerTaxId":string,"issuerForeign":boolean,"number":string,"date":"YYYY-MM-DD","dueDate":"YYYY-MM-DD"|"",
 "currency":string,"exchangeRate":number,"totalCurrency":number,
 "lines":[{"name":string,"unit":string,"qty":number,"price":number}],
 "base":number,"vatRate":number,"vat":number,
 "ecd":string,"duty":number,"vatBase":number,"customsVat":number,"tariffLines":[{"code":string,"value":number}]}
Rules:
- supplier_invoice = commercial invoice from the FOREIGN seller of the goods (usually in EUR/USD, no Macedonian VAT). Fill currency, totalCurrency (invoice total in that currency), lines (price per unit in that currency), issuerName.
- customs_declaration = ЕЦД / Единствена царинска декларација / ЕЦД-ЕЛ. Fill ecd (MRN or declaration number), date, exchangeRate (field 23, курс), currency (field 22), totalCurrency (invoice amount field 22), duty = total customs duty in denars (type A00 in field 47, царина), customsVat = total VAT in denars (type B00, ДДВ), vatBase = base for that VAT in denars, vatRate, tariffLines = per item tariff code (field 33) and customs/statistical value in denars (field 46 or the base in 47). issuerName = "Царинска управа".
- forwarding = invoice from špediter/customs agent (шпедиција) for their service; transport = invoice for freight/превоз; other_cost = any other invoice for costs of this import (insurance, bank fee, storage...). For these fill base (amount without VAT in denars), vatRate (18/10/5/0), vat (denars), issuerName, issuerTaxId, number, date, dueDate. If such an invoice is in foreign currency put currency, totalCurrency and exchangeRate too.
- Amounts are plain numbers (no thousands separators). Dates ISO. Use 0 or "" for missing values. Keep names in the original language.`;

/** Legacy `EMP_PROMPT` (6044–6046) — Phase 6 (TODO(ai): wire `readDocument({ prompt: EMP_PROMPT, purpose: 'emp' })`). */
export const EMP_PROMPT = `This is an employment document from North Macedonia (договор за вработување, решение, М1/М2 пријава, лична карта or similar). Extract the employee. Reply with ONLY JSON:
{"name":string,"embg":string,"address":string,"position":string,"start":"YYYY-MM-DD","end":"YYYY-MM-DD"|"","contract":"неопределено"|"определено"|"","hoursWeek":number,"netSalary":number,"grossSalary":number,"bankAcc":string,"bank":string,"stazPrevYears":number}
Rules: embg = 13-digit ЕМБГ. netSalary/grossSalary in denars per month (0 if not stated). hoursWeek 40 if full time. Keep names in original language (Cyrillic if written so).`;

/** Legacy `BLG_PROMPT` (6525–6527) — Phase 4 cash register (TODO(ai): wire `readDocument({ prompt: BLG_PROMPT, purpose: 'blg' })`). */
export const BLG_PROMPT = `These are receipts or invoices (fiscal receipts, fuel station receipts, toll/vignette/ferry/tunnel tickets, parking, hotel, restaurant, vehicle service, taxi…) from ANY country, paid by an employee of a company from North Macedonia (often a truck driver travelling through Europe). Extract EVERY receipt visible. Reply with ONLY JSON:
{"receipts":[{"country":"ISO 3166-1 alpha-2 of the merchant (MK, AL, XK, RS, BG, GR, HR, SI, AT, DE, IT, FR, NL, BE, HU, RO, CZ, SK, PL, CH, TR…)","currency":"ISO 4217 of the TOTAL (MKD, EUR, RSD, BGN, HUF, RON, CZK, PLN, CHF, ALL, TRY…)","date":"YYYY-MM-DD","docNo":"receipt / fiscal / invoice number exactly as printed (e.g. 'ФИСКАЛЕН БРОЈ 0012345', 'Beleg-Nr. 4711', 'Bon fiscal 123', 'Nr. paragonu 55', 'Račun br. 12-3-4'); prefer the fiscal receipt number","merchant":"company / station name","vatId":"VAT or tax number of the merchant, if printed","total":number,"vatRate":number,"vatAmount":number,"category":"fuel"|"toll"|"parking"|"accommodation"|"food"|"vehicle"|"transport"|"office"|"post"|"other","payment":"cash"|"card"|"other","liters":number|null}]}
Rules: total = the final amount actually paid (incl. VAT), in the receipt currency – on Macedonian fiscal receipts it is next to ВКУПНО / ВКУПЕН ИЗНОС / ЗА НАПЛАТА / ГОТОВИНА; on German SUMME / GESAMT / ZU ZAHLEN; Serbian/Croatian UKUPNO; Italian TOTALE. total MUST be a JSON number, never empty when any amount is visible. docNo: only the number itself (without words like 'ФИСКАЛЕН БРОЈ', 'БР:', 'Beleg-Nr.'). Numbers are written differently per country (1.234,56 in DE/AT/IT/MK/RS…; 1,234.56 in GB/CH/US) – return plain JSON numbers (1234.56). Dates: European receipts are DD.MM.YYYY or DD/MM/YYYY; never swap day and month for European receipts. vatRate: the main VAT % on the receipt (MK 18/10/5 – in North Macedonia fuel (гориво, дизел, бензин) is 10%; read the rate printed on the receipt, DE 19, AT 20, IT 22, HR 25, HU 27, RS 20, BG 20, GR 24, SI 22, FR 20, NL 21…); 0 if none. If a value is not visible use "" or 0. Do not invent receipts.`;

/** Legacy `SCR_PROMPT` (16201–16210) — supplier return / credit note scan. */
export const SCR_PROMPT = (firm: { name?: string | null; edb?: string | null }) => `This document is a GOODS RETURN NOTE (повратница) or a CREDIT NOTE (одобрение / книжно одобрение / кредит нота) between our company and its SUPPLIER, in North Macedonia.
Our company is: "${firm.name || ''}" (ЕДБ ${firm.edb || '?'}). The OTHER party is the supplier – return the supplier's data, never ours (the document may be issued by us or by the supplier).
Reply with ONLY JSON:
{"docType":"return"|"credit","supplierName":string,"supplierEdb":string,"number":string,"date":"YYYY-MM-DD","refInvoice":string,"reason":string,
"lines":[{"code":string,"barcode":string,"name":string,"unit":string,"qty":number,"price":number,"amount":number,"rate":18|10|5|0}],
"groups":[{"rate":18|10|5|0,"base":number,"vat":number}],"total":number}
Rules: docType="return" when goods are physically returned (повратница, враќање стока, рекламација with articles and quantities); "credit" for a discount/price correction without returning goods (одобрение, попуст, рабат, кредит нота).
refInvoice = number of the original invoice the document refers to ("по фактура бр.", "кон ф-ра", "реф.") or "" if none.
All quantities and amounts as POSITIVE plain numbers even if printed with minus. price = unit price WITHOUT VAT. groups from the VAT recapitulation (основица / ДДВ per rate). total = total with VAT.
NUMBER FORMAT: comma is the decimal separator, dot the thousands separator ("1.333,34" = 1333.34). NEVER take quantity from the ДДВ % column. Keep names in the original language.`;
