/**
 * Schema — finance legacy-parity pass (2026-10). New tables only; migrations are generated by the coordinator.
 *
 * - `journal_overrides`: manual line corrections of document journals (legacy `ed` / `edAdd` on the document,
 *   `nalSaveRows` 3580), re-applied by the posting service every time the source document is re-posted.
 */
import { jsonb, pgTable, text, timestamp, uniqueIndex, uuid } from 'drizzle-orm/pg-core';
import { firms, users } from './foundation';

/** Override payload stored as jsonb (shape of `@wise/core/finpar` `JournalOverride`). */
export interface JournalOverrideData {
  edits: { i: number; k0: string; d0: number; p0: number; account?: string; debit?: number; credit?: number; partnerId?: string | null; note?: string | null; doc?: string | null; del?: boolean }[];
  adds: { account: string; debit: number; credit: number; partnerId?: string | null; note?: string | null; doc?: string | null }[];
}
/** Generated lines the edits refer to (refreshed on every posting of the source). */
export interface JournalOverrideBase { account: string; debit: number; credit: number; partnerId?: string | null; note?: string | null; doc?: string | null; currency?: string | null; amountCur?: number | null; locationId?: string | null }

export const journalOverrides = pgTable('journal_overrides', {
  id: uuid('id').primaryKey().defaultRandom(),
  firmId: uuid('firm_id').notNull().references(() => firms.id, { onDelete: 'cascade' }),
  sourceType: text('source_type').notNull(),
  sourceId: text('source_id').notNull(),
  data: jsonb('data').$type<JournalOverrideData>().notNull().default({ edits: [], adds: [] }),
  base: jsonb('base').$type<JournalOverrideBase[]>().notNull().default([]),
  updatedBy: uuid('updated_by').references(() => users.id, { onDelete: 'set null' }),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow().$onUpdate(() => new Date()),
}, (t) => [uniqueIndex('journal_overrides_source_uq').on(t.firmId, t.sourceType, t.sourceId)]);

export type JournalOverrideRow = typeof journalOverrides.$inferSelect;
