/**
 * Schema — tables added by the 2026-10 legacy parity pass over the Фирми / Канцеларија / Архива / Систем / Помош /
 * Анализи views (`docs/parity/firms-office.md`). Simple per-firm options stay in `firms.settings`, office-wide
 * options in `app_settings`; only data with rows of its own gets a table here (append below, one block per table).
 *
 * Migrations are generated by the coordinator after merging.
 */
import { index, jsonb, pgTable, text, timestamp, uuid } from 'drizzle-orm/pg-core';
import { firms, users } from './foundation';

const ts = (name: string) => timestamp(name, { withTimezone: true });


/* ---- tables (append) ---- */

/**
 * Legacy `appaml/r…` (VIEWS.aml tab „🚩 Пријави“, `amlRepNew` / `amlRepSt`): internal suspicion reports to the
 * AML officer. Seen only by the owner (admin) and the officer; status нова → анализа → пријавено во УФР / затворено.
 */
export const amlReports = pgTable('aml_reports', {
  id: uuid('id').primaryKey().defaultRandom(),
  /**
   * The client concerned. Deliberately not `firm_id`: these are the office's records, so they must never travel in
   * the client's per-firm export / backup (ЗСППФТ ban on disclosure).
   */
  firmId: uuid('client_firm_id').references(() => firms.id, { onDelete: 'set null' }),
  firmName: text('firm_name').notNull().default(''),
  text: text('text').notNull(),
  status: text('status').notNull().default('нова'),
  note: text('note'),
  data: jsonb('data').$type<Record<string, unknown>>().notNull().default({}),
  createdBy: uuid('created_by').references(() => users.id, { onDelete: 'set null' }),
  createdByName: text('created_by_name').notNull().default(''),
  createdAt: ts('created_at').notNull().defaultNow(),
}, (t) => [index('aml_reports_created_idx').on(t.createdAt)]);
