/**
 * Schema — tables added by the 2026-10 legacy parity pass over the Фирми / Канцеларија / Архива / Систем / Помош /
 * Анализи views (`docs/parity/firms-office.md`). Simple per-firm options stay in `firms.settings`, office-wide
 * options in `app_settings`; only data with rows of its own gets a table here (append below, one block per table).
 *
 * Migrations are generated by the coordinator after merging.
 */
import { index, jsonb, pgTable, text, timestamp, uuid } from 'drizzle-orm/pg-core';
import { firms, users } from './foundation';

const ts = (name: string) => timestamp(name, { withTimezone: true });
void [index, jsonb, pgTable, text, uuid, firms, users, ts];

/* ---- tables (append) ---- */
